/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Pc
 */
public class NewFamily extends javax.swing.JFrame {

    /**
     * Creates new form Ananya
     */
    public NewFamily() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        Cart = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        CartItem = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel285 = new javax.swing.JLabel();
        It2 = new javax.swing.JLabel();
        It1 = new javax.swing.JLabel();
        It3 = new javax.swing.JLabel();
        It5 = new javax.swing.JLabel();
        It4 = new javax.swing.JLabel();
        R1 = new javax.swing.JLabel();
        R2 = new javax.swing.JLabel();
        R3 = new javax.swing.JLabel();
        R4 = new javax.swing.JLabel();
        R5 = new javax.swing.JLabel();
        GrandTotal = new javax.swing.JLabel();
        jLabel286 = new javax.swing.JLabel();
        Totalrs = new javax.swing.JLabel();
        jLabel287 = new javax.swing.JLabel();
        CheckOut = new javax.swing.JButton();
        jPanel27 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jPanel28 = new javax.swing.JPanel();
        jLabel298 = new javax.swing.JLabel();
        jLabel299 = new javax.swing.JLabel();
        jLabel300 = new javax.swing.JLabel();
        jLabel301 = new javax.swing.JLabel();
        jLabel302 = new javax.swing.JLabel();
        jLabel303 = new javax.swing.JLabel();
        jLabel304 = new javax.swing.JLabel();
        jLabel305 = new javax.swing.JLabel();
        jLabel306 = new javax.swing.JLabel();
        jLabel307 = new javax.swing.JLabel();
        jLabel308 = new javax.swing.JLabel();
        jLabel309 = new javax.swing.JLabel();
        jLabel310 = new javax.swing.JLabel();
        jLabel311 = new javax.swing.JLabel();
        jLabel312 = new javax.swing.JLabel();
        jLabel313 = new javax.swing.JLabel();
        jLabel314 = new javax.swing.JLabel();
        jLabel315 = new javax.swing.JLabel();
        jLabel316 = new javax.swing.JLabel();
        jLabel317 = new javax.swing.JLabel();
        jLabel318 = new javax.swing.JLabel();
        jLabel319 = new javax.swing.JLabel();
        jLabel320 = new javax.swing.JLabel();
        jLabel321 = new javax.swing.JLabel();
        jLabel322 = new javax.swing.JLabel();
        Max11 = new javax.swing.JLabel();
        Max = new javax.swing.JLabel();
        jPanel29 = new javax.swing.JPanel();
        jLabel323 = new javax.swing.JLabel();
        It6 = new javax.swing.JLabel();
        It7 = new javax.swing.JLabel();
        It8 = new javax.swing.JLabel();
        It9 = new javax.swing.JLabel();
        It10 = new javax.swing.JLabel();
        R6 = new javax.swing.JLabel();
        R7 = new javax.swing.JLabel();
        R8 = new javax.swing.JLabel();
        R9 = new javax.swing.JLabel();
        R10 = new javax.swing.JLabel();
        GrandTotal1 = new javax.swing.JLabel();
        jLabel324 = new javax.swing.JLabel();
        Totalrs1 = new javax.swing.JLabel();
        jLabel325 = new javax.swing.JLabel();
        CheckOut1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 204));

        jPanel14.setBackground(new java.awt.Color(247, 247, 247));

        jPanel15.setBackground(new java.awt.Color(102, 255, 0));

        jButton1.setBackground(new java.awt.Color(102, 255, 51));
        jButton1.setText("Go Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel53.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        jLabel53.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel53.setText("HotServe");

        jLabel54.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel54.setText("Eat Sleep Repeat");

        Cart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/cart1.png"))); // NOI18N
        Cart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CartMouseClicked(evt);
            }
        });

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/newlogo - Copy.jpeg"))); // NOI18N

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addGap(334, 334, 334)
                        .addComponent(jLabel53))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGap(465, 465, 465)
                        .addComponent(jLabel54)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 304, Short.MAX_VALUE)
                .addComponent(Cart)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CartItem)
                .addGap(31, 31, 31))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel54))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Cart)
                            .addComponent(CartItem))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel16.setBackground(new java.awt.Color(255, 255, 204));
        jPanel16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel19.setText("WELCOME TO NEW FAMILY");

        jLabel1.setText("NEAR SRM IST, MODINAGAR(GHAZIABAD)");

        jLabel2.setText("Minimum Cost Must be Rs.100");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/4.jpg"))); // NOI18N

        jLabel17.setText("Maximum you can select only 5 items at a time");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 711, Short.MAX_VALUE)
                        .addGap(227, 227, 227))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel3)
                .addGap(29, 29, 29))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel24.setBackground(new java.awt.Color(255, 255, 204));

        jLabel285.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel285.setText("Items selected");

        R1.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N

        R2.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N

        R3.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N

        R4.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N

        R5.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N

        GrandTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel286.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        Totalrs.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel287.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel287.setText("CALCULATE TOTAL");
        jLabel287.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel287MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel285))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(It1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                                .addComponent(R1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(It2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(R2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(It3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(R3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(It5, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(GrandTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(It4, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel287))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(R4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(R5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel286))))))
                .addGap(153, 153, 153))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Totalrs, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(167, 167, 167))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel285)
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R1)
                    .addComponent(It1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(It2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(R2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(It3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(R3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(It4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(R4, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(It5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(R5))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel286, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel287)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(GrandTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Totalrs, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                        .addGap(20, 20, 20))))
        );

        CheckOut.setBackground(new java.awt.Color(102, 255, 0));
        CheckOut.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        CheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckOutActionPerformed(evt);
            }
        });

        jPanel27.setBackground(new java.awt.Color(255, 255, 204));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel20.setText("FOOD MENU");

        jLabel298.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel298.setText("VEG :");

        jLabel299.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel299.setText("* AALU PRATHA");

        jLabel300.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel300.setText("* PANEER PRATHA");

        jLabel301.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel301.setText("* BUTTER NAN");

        jLabel302.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel302.setText("* CHHOLE BHATURE");

        jLabel303.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel303.setText("* CHILLI POTATO");

        jLabel304.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel304.setText("* MALAI  KOFTA");

        jLabel305.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel305.setText("* PALAK PANEER");

        jLabel306.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel306.setText("* BREAD PIZZA");

        jLabel307.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel307.setText("RS. 50");

        jLabel308.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel308.setText("RS. 50");

        jLabel309.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel309.setText("RS. 30");

        jLabel310.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel310.setText("RS. 40 ");

        jLabel311.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel311.setText("RS. 70");

        jLabel312.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel312.setText("RS. 100");

        jLabel313.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel313.setText("RS. 80");

        jLabel314.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel314.setText("RS. 30");

        jLabel315.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel315.setForeground(new java.awt.Color(51, 153, 0));
        jLabel315.setText("Add to Cart");
        jLabel315.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel315MouseClicked(evt);
            }
        });

        jLabel316.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel316.setForeground(new java.awt.Color(51, 153, 0));
        jLabel316.setText("Add to Cart");
        jLabel316.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel316MouseClicked(evt);
            }
        });

        jLabel317.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel317.setForeground(new java.awt.Color(51, 153, 0));
        jLabel317.setText("Add to Cart");
        jLabel317.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel317MouseClicked(evt);
            }
        });

        jLabel318.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel318.setForeground(new java.awt.Color(51, 153, 0));
        jLabel318.setText("Add to Cart");
        jLabel318.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel318MouseClicked(evt);
            }
        });

        jLabel319.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel319.setForeground(new java.awt.Color(51, 153, 0));
        jLabel319.setText("Add to Cart");
        jLabel319.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel319MouseClicked(evt);
            }
        });

        jLabel320.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel320.setForeground(new java.awt.Color(51, 153, 0));
        jLabel320.setText("Add to Cart");
        jLabel320.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel320MouseClicked(evt);
            }
        });

        jLabel321.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel321.setForeground(new java.awt.Color(51, 153, 0));
        jLabel321.setText("Add to Cart");
        jLabel321.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel321MouseClicked(evt);
            }
        });

        jLabel322.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel322.setForeground(new java.awt.Color(51, 153, 0));
        jLabel322.setText("Add to Cart");
        jLabel322.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel322MouseClicked(evt);
            }
        });

        Max11.setForeground(new java.awt.Color(255, 51, 51));

        Max.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel28Layout = new javax.swing.GroupLayout(jPanel28);
        jPanel28.setLayout(jPanel28Layout);
        jPanel28Layout.setHorizontalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel28Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel28Layout.createSequentialGroup()
                            .addComponent(jLabel301)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel309, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel28Layout.createSequentialGroup()
                            .addComponent(jLabel299)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel308, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel28Layout.createSequentialGroup()
                            .addComponent(jLabel306)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel314, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel28Layout.createSequentialGroup()
                            .addComponent(jLabel302)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel310, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel28Layout.createSequentialGroup()
                            .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel305)
                                .addComponent(jLabel303))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel311, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel312, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel28Layout.createSequentialGroup()
                            .addComponent(jLabel304)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel313, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel28Layout.createSequentialGroup()
                        .addComponent(jLabel300, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89)
                        .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel307, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Max))))
                .addGap(30, 30, 30)
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel315)
                    .addComponent(jLabel316)
                    .addComponent(jLabel317)
                    .addComponent(jLabel318)
                    .addComponent(jLabel319)
                    .addComponent(jLabel320)
                    .addComponent(jLabel321)
                    .addComponent(jLabel322))
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(jPanel28Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel298, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(Max11, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel28Layout.setVerticalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel28Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel298)
                    .addComponent(Max11))
                .addGap(4, 4, 4)
                .addComponent(Max)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel300, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel307)
                    .addComponent(jLabel315))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel28Layout.createSequentialGroup()
                        .addComponent(jLabel299, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel301, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel309)
                            .addComponent(jLabel317))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel302, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel310)
                            .addComponent(jLabel318)))
                    .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel308)
                        .addComponent(jLabel316)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel28Layout.createSequentialGroup()
                        .addComponent(jLabel303, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel305, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel312)
                            .addComponent(jLabel320))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel304, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel313)
                            .addComponent(jLabel322)))
                    .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel311)
                        .addComponent(jLabel319)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel306, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel314)
                    .addComponent(jLabel321))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel323.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel323.setText("Items selected");

        R6.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N

        R7.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N

        R8.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N

        R9.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N

        R10.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N

        GrandTotal1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel324.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        Totalrs1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel325.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel325.setText("CALCULATE TOTAL");
        jLabel325.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel325MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel29Layout = new javax.swing.GroupLayout(jPanel29);
        jPanel29.setLayout(jPanel29Layout);
        jPanel29Layout.setHorizontalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel29Layout.createSequentialGroup()
                .addGroup(jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel29Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel323))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel29Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel29Layout.createSequentialGroup()
                                .addComponent(It7, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                                .addComponent(R6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel29Layout.createSequentialGroup()
                                .addComponent(It6, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(R7, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel29Layout.createSequentialGroup()
                                .addComponent(It8, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(R8, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel29Layout.createSequentialGroup()
                                .addGroup(jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(It9, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(GrandTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(It10, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel325))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(R9, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(R10, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel324))))))
                .addGap(153, 153, 153))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel29Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Totalrs1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(167, 167, 167))
        );
        jPanel29Layout.setVerticalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel29Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel323)
                .addGap(27, 27, 27)
                .addGroup(jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R6)
                    .addComponent(It7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(It6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(R7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(It8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(R8))
                .addGap(18, 18, 18)
                .addGroup(jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(It10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(R9, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(It9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(R10))
                .addGroup(jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel29Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel324, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel29Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel325)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(GrandTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Totalrs1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20))))
        );

        CheckOut1.setBackground(new java.awt.Color(102, 255, 0));
        CheckOut1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        CheckOut1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckOut1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel27Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jPanel28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel27Layout.createSequentialGroup()
                .addContainerGap(520, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addGap(241, 241, 241)
                .addComponent(CheckOut1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel27Layout.setVerticalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel27Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckOut1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel27Layout.createSequentialGroup()
                        .addComponent(jPanel28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 11, Short.MAX_VALUE))
                    .addComponent(jPanel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addContainerGap(576, Short.MAX_VALUE)
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
            .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel24Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 42, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel24Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        HomePage h=new HomePage();
        h.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CartMouseClicked
    //        h.setVisible(true);
       //Cart.CartHeading.setText("WELCOME TO NEW FAMILY");
      //  dispose();
    }//GEN-LAST:event_CartMouseClicked
int f=0;
    private void jLabel287MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel287MouseClicked
        //@LAKSHAY(RA1711003030064)

        if(iii==1)
        {
            a=Integer.valueOf(R1.getText());
            b=0;
            c=0;
            d=0;
            e=0;
        }
        else if(iii==2)
        {
            a=Integer.valueOf(R1.getText());

            b=Integer.valueOf(R2.getText());
            c=0;d=0;e=0;
        }

        else if(iii==3)
        {
            a=Integer.valueOf(R1.getText());

            b=Integer.valueOf(R2.getText());
            c=Integer.valueOf(R3.getText());
            d=0;
            e=0;

        }
        else if(iii==4)
        {
            a=Integer.valueOf(R1.getText());

            b=Integer.valueOf(R2.getText());
            c=Integer.valueOf(R3.getText());
            e=0;
            d=Integer.valueOf(R4.getText());
        }
        //c=Integer.valueOf(R3.getText());
        //d=Integer.valueOf(R4.getText());
        //e=Integer.valueOf(R5.getText());
        else if(iii==5)
        {
            a=Integer.valueOf(R1.getText());

            b=Integer.valueOf(R2.getText());
            c=Integer.valueOf(R3.getText());
            e=Integer.valueOf(R5.getText());
            d=Integer.valueOf(R4.getText());

        }
         f=a+b+c+d+e;
        if(f>=100)
        {
            CheckOut.setText("PROCEED TO CHECKOUT");
        }
        if(f<100)
        {
            Max.setText("Order value must be above 100");
        }
        else
        {
            String s=Integer.toString(f);
            GrandTotal.setText("GRAND TOTAL");
            Totalrs.setText(s);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel287MouseClicked

    private void jLabel315MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel315MouseClicked

        //Cart c=new Cart();
        //c.setItem();
        //@LAKSHAY(RA1711003030064)
        Max.setText("");
        iii=iii+1;
        if(iii==1)
        {
            CartItem.setText("1");
            It1.setText("PANEER PRATHA");//if (i1.equals(""))
            R1.setText("50");
        }
        else  if(iii==2)
        {
            CartItem.setText("2");
            It2.setText("PANEER PRATHA");//if (i1.equals(""))
            R2.setText("50");
        }
        else  if(iii==3)
        {
            CartItem.setText("3");
            It3.setText("PANEER PRATHA");//if (i1.equals(""))
            R3.setText("50");
        }
        else  if(iii==4)
        {
            CartItem.setText("4");
            It4.setText("PANEER PRATHA");//if (i1.equals(""))
            R4.setText("50");
        }
        else  if(iii==5)
        {
            CartItem.setText("5");
            R5.setText("50");
            It5.setText("PANEER PRATHA");//if (i1.equals(""))
        }
        else
        {
            Max.setText("*Sorry You cannot add more than 5 Items");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel315MouseClicked

    private void jLabel316MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel316MouseClicked
        //@LAKSHAY(RA1711003030064)
        Max.setText("");
        iii=iii+1;
        if(iii==1)
        {
            CartItem.setText("1");
            It1.setText("AALU PRATHA");//if (i1.equals(""))
            R1.setText("50");
        }
        else  if(iii==2)
        {
            CartItem.setText("2");
            It2.setText("AALU PRATHA");//if (i1.equals(""))
            R2.setText("50");
        }
        else  if(iii==3)
        {
            CartItem.setText("3");
            It3.setText("AALU PRATHA");//if (i1.equals(""))
            R3.setText("50");
        }
        else  if(iii==4)
        {
            CartItem.setText("4");
            It4.setText("AALU PRATHA");//if (i1.equals(""))
            R4.setText("50");
        }
        else  if(iii==5)
        {
            CartItem.setText("5");
            R5.setText("50");
            It5.setText("AALU PRATHA");//if (i1.equals(""))
        }
        else
        {
            Max.setText("*Sorry You cannot add more than 5 Items");
        }
    }//GEN-LAST:event_jLabel316MouseClicked

    private void jLabel317MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel317MouseClicked
        //@LAKSHAY(RA1711003030064)
        Max.setText("");
        iii=iii+1;
        if(iii==1)
        {
            CartItem.setText("1");
            It1.setText("BUTTER NAN");//if (i1.equals(""))
            R1.setText("30");
        }
        else  if(iii==2)
        {
            CartItem.setText("2");
            It2.setText("BUTTER NAN");//if (i1.equals(""))
            R2.setText("30");
        }
        else  if(iii==3)
        {
            CartItem.setText("3");
            It3.setText("BUTTER NAN");//if (i1.equals(""))
            R3.setText("30");
        }
        else  if(iii==4)
        {
            CartItem.setText("4");
            It4.setText("BUTTER NAN");//if (i1.equals(""))
            R4.setText("30");
        }
        else  if(iii==5)
        {
            CartItem.setText("5");
            R5.setText("30");
            It5.setText("BUTTER NAN");//if (i1.equals(""))
        }
        else
        {
            Max.setText("*Sorry You cannot add more than 5 Items");
        }
    }//GEN-LAST:event_jLabel317MouseClicked

    private void jLabel318MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel318MouseClicked
        //@LAKSHAY(RA1711003030064)
        Max.setText("");
        iii=iii+1;
        if(iii==1)
        {
            CartItem.setText("1");
            It1.setText("CHHOLE BHATURE");//if (i1.equals(""))
            R1.setText("40");
        }
        else  if(iii==2)
        {
            CartItem.setText("2");
            It2.setText("CHHOLE BHATURE");//if (i1.equals(""))
            R2.setText("40");
        }
        else  if(iii==3)
        {
            CartItem.setText("3");
            It3.setText("CHHOLE BHATURE");//if (i1.equals(""))
            R3.setText("40");
        }
        else  if(iii==4)
        {
            CartItem.setText("4");
            It4.setText("CHHOLE BHATURE");//if (i1.equals(""))
            R4.setText("40");
        }
        else  if(iii==5)
        {
            CartItem.setText("5");
            R5.setText("40");
            It5.setText("CHHOLE BHATURE");//if (i1.equals(""))
        }
        else
        {
            Max.setText("*Sorry You cannot add more than 5 Items");
        }
    }//GEN-LAST:event_jLabel318MouseClicked

    private void jLabel319MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel319MouseClicked
        //@LAKSHAY(RA1711003030064)
        Max.setText("");
        iii=iii+1;
        if(iii==1)
        {
            CartItem.setText("1");
            It1.setText("CHILLI POTATO");//if (i1.equals(""))
            R1.setText("70");
        }
        else  if(iii==2)
        {
            CartItem.setText("2");
            It2.setText("CHILLI POTATO");//if (i1.equals(""))
            R2.setText("70");
        }
        else  if(iii==3)
        {
            CartItem.setText("3");
            It3.setText("CHILLI POTATO");//if (i1.equals(""))
            R3.setText("70");
        }
        else  if(iii==4)
        {
            CartItem.setText("4");
            It4.setText("CHILLI POTATO");//if (i1.equals(""))
            R4.setText("70");
        }
        else  if(iii==5)
        {
            CartItem.setText("5");
            R5.setText("70");
            It5.setText("CHILLI POTATO");//if (i1.equals(""))
        }
        else
        {
            Max.setText("*Sorry You cannot add more than 5 Items");
        }
    }//GEN-LAST:event_jLabel319MouseClicked

    private void jLabel320MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel320MouseClicked
        //@LAKSHAY(RA1711003030064)
        Max.setText("");
        iii=iii+1;
        if(iii==1)
        {
            CartItem.setText("1");
            It1.setText("PALAK PANEER");//if (i1.equals(""))
            R1.setText("100");
        }
        else  if(iii==2)
        {
            CartItem.setText("2");
            It2.setText("PALAK PANEER");//if (i1.equals(""))
            R2.setText("100");
        }
        else  if(iii==3)
        {
            CartItem.setText("3");
            It3.setText("PALAK PANEER");//if (i1.equals(""))
            R3.setText("100");
        }
        else  if(iii==4)
        {
            CartItem.setText("4");
            It4.setText("PALAK PANEER");//if (i1.equals(""))
            R4.setText("100");
        }
        else  if(iii==5)
        {
            CartItem.setText("5");
            R5.setText("100");
            It5.setText("PALAK PANEER");//if (i1.equals(""))
        }
        else
        {
            Max.setText("*Sorry You cannot add more than 5 Items");
        }
    }//GEN-LAST:event_jLabel320MouseClicked

    private void jLabel321MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel321MouseClicked
        //@LAKSHAY(RA1711003030064)
        Max.setText("");
        iii=iii+1;
        if(iii==1)
        {
            CartItem.setText("1");
            It1.setText("BREAD PIZZA");//if (i1.equals(""))
            R1.setText("30");
        }
        else  if(iii==2)
        {
            CartItem.setText("2");
            It2.setText("BREAD PIZZA");//if (i1.equals(""))
            R2.setText("30");
        }
        else  if(iii==3)
        {
            CartItem.setText("3");
            It3.setText("BREAD PIZZA");//if (i1.equals(""))
            R3.setText("30");
        }
        else  if(iii==4)
        {
            CartItem.setText("4");
            It4.setText("BREAD PIZZA");//if (i1.equals(""))
            R4.setText("30");
        }
        else  if(iii==5)
        {
            CartItem.setText("5");
            R5.setText("30");
            It5.setText("BREAD PIZZA");//if (i1.equals(""))
        }
        else
        {
            Max.setText("*Sorry You cannot add more than 5 Items");
        }
    }//GEN-LAST:event_jLabel321MouseClicked

    private void jLabel322MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel322MouseClicked
        //@LAKSHAY(RA1711003030064)
        Max.setText("");
        iii=iii+1;
        if(iii==1)
        {
            CartItem.setText("1");
            It1.setText("MALAI KOFTA");//if (i1.equals(""))
            R1.setText("80");
        }
        else  if(iii==2)
        {
            CartItem.setText("2");
            It2.setText("MALAI KOFTA");//if (i1.equals(""))
            R2.setText("80");
        }
        else  if(iii==3)
        {
            CartItem.setText("3");
            It3.setText("MALAI KOFTA");//if (i1.equals(""))
            R3.setText("80");
        }
        else  if(iii==4)
        {
            CartItem.setText("4");
            It4.setText("MALAI KOFTA");//if (i1.equals(""))
            R4.setText("80");
        }
        else  if(iii==5)
        {
            CartItem.setText("5");
            R5.setText("80");
            It5.setText("MALAI KOFTA");//if (i1.equals(""))
        }
        else
        {
            Max.setText("*Sorry You cannot add more than 5 Items");
        }

    }//GEN-LAST:event_jLabel322MouseClicked

    private void jLabel325MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel325MouseClicked
        //@LAKSHAY(RA1711003030064)

        if(iii==1)
        {
            a=Integer.valueOf(R1.getText());
            b=0;
            c=0;
            d=0;
            e=0;
        }
        else if(iii==2)
        {
            a=Integer.valueOf(R1.getText());

            b=Integer.valueOf(R2.getText());
            c=0;d=0;e=0;
        }

        else if(iii==3)
        {
            a=Integer.valueOf(R1.getText());

            b=Integer.valueOf(R2.getText());
            c=Integer.valueOf(R3.getText());
            d=0;
            e=0;

        }
        else if(iii==4)
        {
            a=Integer.valueOf(R1.getText());

            b=Integer.valueOf(R2.getText());
            c=Integer.valueOf(R3.getText());
            e=0;
            d=Integer.valueOf(R4.getText());
        }
        //c=Integer.valueOf(R3.getText());
        //d=Integer.valueOf(R4.getText());
        //e=Integer.valueOf(R5.getText());
        else if(iii==5)
        {
            a=Integer.valueOf(R1.getText());

            b=Integer.valueOf(R2.getText());
            c=Integer.valueOf(R3.getText());
            e=Integer.valueOf(R5.getText());
            d=Integer.valueOf(R4.getText());

        }
        int f=a+b+c+d+e;
        if(f>=100)
        {
            CheckOut.setText("PROCEED TO CHECKOUT");
        }
        if(f<100)
        {
            Max.setText("Order value must be above 100");
        }
        else
        {
            String s=Integer.toString(f);
            GrandTotal.setText("GRAND TOTAL");
            Totalrs.setText(s);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel325MouseClicked

    private void CheckOut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckOut1ActionPerformed
if(f>=100)
       {
        Payment h=new Payment();
        h.setVisible(true);
        
        dispose();// TODO add your handling code here:
       }    }//GEN-LAST:event_CheckOut1ActionPerformed

    private void CheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckOutActionPerformed
        Payment h=new Payment();
        h.setVisible(true);
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_CheckOutActionPerformed
static int iii=0;
int a=0,b=0,c=0,d=0,e=0;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewFamily.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewFamily.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewFamily.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewFamily.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewFamily().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cart;
    private javax.swing.JLabel CartItem;
    private javax.swing.JButton CheckOut;
    private javax.swing.JButton CheckOut1;
    private javax.swing.JLabel GrandTotal;
    private javax.swing.JLabel GrandTotal1;
    private javax.swing.JLabel It1;
    private javax.swing.JLabel It10;
    private javax.swing.JLabel It2;
    private javax.swing.JLabel It3;
    private javax.swing.JLabel It4;
    private javax.swing.JLabel It5;
    private javax.swing.JLabel It6;
    private javax.swing.JLabel It7;
    private javax.swing.JLabel It8;
    private javax.swing.JLabel It9;
    private javax.swing.JLabel Max;
    private javax.swing.JLabel Max11;
    private javax.swing.JLabel R1;
    private javax.swing.JLabel R10;
    private javax.swing.JLabel R2;
    private javax.swing.JLabel R3;
    private javax.swing.JLabel R4;
    private javax.swing.JLabel R5;
    private javax.swing.JLabel R6;
    private javax.swing.JLabel R7;
    private javax.swing.JLabel R8;
    private javax.swing.JLabel R9;
    private javax.swing.JLabel Totalrs;
    private javax.swing.JLabel Totalrs1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel285;
    private javax.swing.JLabel jLabel286;
    private javax.swing.JLabel jLabel287;
    private javax.swing.JLabel jLabel298;
    private javax.swing.JLabel jLabel299;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel300;
    private javax.swing.JLabel jLabel301;
    private javax.swing.JLabel jLabel302;
    private javax.swing.JLabel jLabel303;
    private javax.swing.JLabel jLabel304;
    private javax.swing.JLabel jLabel305;
    private javax.swing.JLabel jLabel306;
    private javax.swing.JLabel jLabel307;
    private javax.swing.JLabel jLabel308;
    private javax.swing.JLabel jLabel309;
    private javax.swing.JLabel jLabel310;
    private javax.swing.JLabel jLabel311;
    private javax.swing.JLabel jLabel312;
    private javax.swing.JLabel jLabel313;
    private javax.swing.JLabel jLabel314;
    private javax.swing.JLabel jLabel315;
    private javax.swing.JLabel jLabel316;
    private javax.swing.JLabel jLabel317;
    private javax.swing.JLabel jLabel318;
    private javax.swing.JLabel jLabel319;
    private javax.swing.JLabel jLabel320;
    private javax.swing.JLabel jLabel321;
    private javax.swing.JLabel jLabel322;
    private javax.swing.JLabel jLabel323;
    private javax.swing.JLabel jLabel324;
    private javax.swing.JLabel jLabel325;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    // End of variables declaration//GEN-END:variables
}
