/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Pc
 */
public class Up14 extends javax.swing.JFrame {

    /**
     * Creates new form Ananya
     */
    public Up14() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        Cart = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        CartItem = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel263 = new javax.swing.JLabel();
        jLabel264 = new javax.swing.JLabel();
        jLabel265 = new javax.swing.JLabel();
        jLabel266 = new javax.swing.JLabel();
        jLabel267 = new javax.swing.JLabel();
        jLabel268 = new javax.swing.JLabel();
        jLabel269 = new javax.swing.JLabel();
        jLabel270 = new javax.swing.JLabel();
        jLabel271 = new javax.swing.JLabel();
        jLabel272 = new javax.swing.JLabel();
        jLabel273 = new javax.swing.JLabel();
        jLabel274 = new javax.swing.JLabel();
        jLabel275 = new javax.swing.JLabel();
        jLabel276 = new javax.swing.JLabel();
        jLabel277 = new javax.swing.JLabel();
        jLabel278 = new javax.swing.JLabel();
        jLabel279 = new javax.swing.JLabel();
        jLabel280 = new javax.swing.JLabel();
        jLabel281 = new javax.swing.JLabel();
        jLabel282 = new javax.swing.JLabel();
        jLabel283 = new javax.swing.JLabel();
        jLabel284 = new javax.swing.JLabel();
        Max9 = new javax.swing.JLabel();
        Max = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel285 = new javax.swing.JLabel();
        It2 = new javax.swing.JLabel();
        It1 = new javax.swing.JLabel();
        It3 = new javax.swing.JLabel();
        It5 = new javax.swing.JLabel();
        It4 = new javax.swing.JLabel();
        R1 = new javax.swing.JLabel();
        R2 = new javax.swing.JLabel();
        R3 = new javax.swing.JLabel();
        R4 = new javax.swing.JLabel();
        R5 = new javax.swing.JLabel();
        GrandTotal = new javax.swing.JLabel();
        jLabel286 = new javax.swing.JLabel();
        Totalrs = new javax.swing.JLabel();
        jLabel287 = new javax.swing.JLabel();
        CheckOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 204));

        jPanel14.setBackground(new java.awt.Color(247, 247, 247));

        jPanel15.setBackground(new java.awt.Color(102, 255, 0));

        jButton1.setBackground(new java.awt.Color(102, 255, 51));
        jButton1.setText("Go Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel53.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        jLabel53.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel53.setText("HotServe");

        jLabel54.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel54.setText("Eat Sleep Repeat");

        Cart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/cart1.png"))); // NOI18N
        Cart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CartMouseClicked(evt);
            }
        });

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/newlogo - Copy.jpeg"))); // NOI18N

        CartItem.setText("jLabel37");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addGap(362, 362, 362)
                        .addComponent(jLabel53))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGap(484, 484, 484)
                        .addComponent(jLabel54)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Cart)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CartItem)
                .addGap(26, 26, 26))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel15Layout.createSequentialGroup()
                                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel54))
                            .addGroup(jPanel15Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(Cart))))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(CartItem)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel16.setBackground(new java.awt.Color(255, 255, 204));
        jPanel16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel19.setText("WELCOME TO UP14");

        jLabel1.setText("NEAR SRM IST, MODINAGAR(GHAZIABAD)");

        jLabel2.setText("Minimum Cost Must be Rs.150");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/10.jpg"))); // NOI18N

        jLabel17.setText("Maximum you can select only 5 items at a time");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel16Layout.createSequentialGroup()
                                .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 758, Short.MAX_VALUE)
                                .addGap(227, 227, 227))
                            .addGroup(jPanel16Layout.createSequentialGroup()
                                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jLabel3)
                        .addGap(29, 29, 29))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17))
        );

        jPanel24.setBackground(new java.awt.Color(255, 255, 204));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("FOOD MENU");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("VEG :");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setText("* AALU PRATHA");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setText("* PANEER PRATHA");

        jLabel263.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel263.setText("* BUTTER NAN");

        jLabel264.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel264.setText("* CHHOLE BHATURE");

        jLabel265.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel265.setText("* CHILLI POTATO");

        jLabel266.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel266.setText("* MALAI  KOFTA");

        jLabel267.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel267.setText("* PALAK PANEER");

        jLabel268.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel268.setText("* BREAD PIZZA");

        jLabel269.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel269.setText("RS. 50");

        jLabel270.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel270.setText("RS. 50");

        jLabel271.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel271.setText("RS. 30");

        jLabel272.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel272.setText("RS. 40 ");

        jLabel273.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel273.setText("RS. 70");

        jLabel274.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel274.setText("RS. 100");

        jLabel275.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel275.setText("RS. 80");

        jLabel276.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel276.setText("RS. 30");

        jLabel277.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel277.setForeground(new java.awt.Color(51, 153, 0));
        jLabel277.setText("Add to Cart");
        jLabel277.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel277MouseClicked(evt);
            }
        });

        jLabel278.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel278.setForeground(new java.awt.Color(51, 153, 0));
        jLabel278.setText("Add to Cart");
        jLabel278.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel278MouseClicked(evt);
            }
        });

        jLabel279.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel279.setForeground(new java.awt.Color(51, 153, 0));
        jLabel279.setText("Add to Cart");
        jLabel279.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel279MouseClicked(evt);
            }
        });

        jLabel280.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel280.setForeground(new java.awt.Color(51, 153, 0));
        jLabel280.setText("Add to Cart");
        jLabel280.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel280MouseClicked(evt);
            }
        });

        jLabel281.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel281.setForeground(new java.awt.Color(51, 153, 0));
        jLabel281.setText("Add to Cart");
        jLabel281.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel281MouseClicked(evt);
            }
        });

        jLabel282.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel282.setForeground(new java.awt.Color(51, 153, 0));
        jLabel282.setText("Add to Cart");
        jLabel282.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel282MouseClicked(evt);
            }
        });

        jLabel283.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel283.setForeground(new java.awt.Color(51, 153, 0));
        jLabel283.setText("Add to Cart");
        jLabel283.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel283MouseClicked(evt);
            }
        });

        jLabel284.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel284.setForeground(new java.awt.Color(51, 153, 0));
        jLabel284.setText("Add to Cart");
        jLabel284.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel284MouseClicked(evt);
            }
        });

        Max9.setForeground(new java.awt.Color(255, 51, 51));

        Max.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel23Layout.createSequentialGroup()
                            .addComponent(jLabel263)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel271, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel23Layout.createSequentialGroup()
                            .addComponent(jLabel20)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel270, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel23Layout.createSequentialGroup()
                            .addComponent(jLabel268)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel276, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel23Layout.createSequentialGroup()
                            .addComponent(jLabel264)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel272, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel23Layout.createSequentialGroup()
                            .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel267)
                                .addComponent(jLabel265))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel273, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel274, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel23Layout.createSequentialGroup()
                            .addComponent(jLabel266)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel275, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89)
                        .addComponent(jLabel269, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel277)
                    .addComponent(jLabel278)
                    .addComponent(jLabel279)
                    .addComponent(jLabel280)
                    .addComponent(jLabel281)
                    .addComponent(jLabel282)
                    .addComponent(jLabel283)
                    .addComponent(jLabel284))
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(Max9, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel23Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Max)
                        .addGap(87, 87, 87))))
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(Max9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Max)
                .addGap(18, 18, 18)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel269)
                    .addComponent(jLabel277))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel263, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel271)
                            .addComponent(jLabel279))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel264, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel272)
                            .addComponent(jLabel280)))
                    .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel270)
                        .addComponent(jLabel278)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addComponent(jLabel265, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel267, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel274)
                            .addComponent(jLabel282))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel266, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel275)
                            .addComponent(jLabel284)))
                    .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel273)
                        .addComponent(jLabel281)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel268, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel276)
                    .addComponent(jLabel283))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel285.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel285.setText("Items selected");

        R1.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N

        R2.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N

        R3.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N

        R4.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N

        R5.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N

        GrandTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel286.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        Totalrs.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel287.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel287.setText("CALCULATE TOTAL");
        jLabel287.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel287MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel285))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(It1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                                .addComponent(R1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(It2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(R2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(It3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(R3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(It5, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(GrandTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(It4, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel287))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(R4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(R5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel286))))))
                .addGap(153, 153, 153))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Totalrs, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(167, 167, 167))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel285)
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R1)
                    .addComponent(It1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(It2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(R2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(It3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(R3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(It4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(R4, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(It5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(R5))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel286, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel287)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(GrandTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Totalrs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20))))
        );

        CheckOut.setBackground(new java.awt.Color(102, 255, 0));
        CheckOut.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        CheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel24Layout.createSequentialGroup()
                        .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel24Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(234, 234, 234)
                        .addComponent(CheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel24Layout.createSequentialGroup()
                        .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        HomePage h=new HomePage();
        h.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CartMouseClicked
    }//GEN-LAST:event_CartMouseClicked

    private void jLabel277MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel277MouseClicked

        //Cart c=new Cart();
        //c.setItem();
        //@LAKSHAY(RA1711003030064)
        Max.setText("");
        iii=iii+1;
        if(iii==1)
        {
            CartItem.setText("1");
            It1.setText("PANEER PRATHA");//if (i1.equals(""))
            R1.setText("50");
        }
        else  if(iii==2)
        {
            CartItem.setText("2");
            It2.setText("PANEER PRATHA");//if (i1.equals(""))
            R2.setText("50");
        }
        else  if(iii==3)
        {
            CartItem.setText("3");
            It3.setText("PANEER PRATHA");//if (i1.equals(""))
            R3.setText("50");
        }
        else  if(iii==4)
        {
            CartItem.setText("4");
            It4.setText("PANEER PRATHA");//if (i1.equals(""))
            R4.setText("50");
        }
        else  if(iii==5)
        {
            CartItem.setText("5");
            R5.setText("50");
            It5.setText("PANEER PRATHA");//if (i1.equals(""))
        }
        else
        {
            Max.setText("*Sorry You cannot add more than 5 Items");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel277MouseClicked

    private void jLabel278MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel278MouseClicked
        //@LAKSHAY(RA1711003030064)
        Max.setText("");
        iii=iii+1;
        if(iii==1)
        {
            CartItem.setText("1");
            It1.setText("AALU PRATHA");//if (i1.equals(""))
            R1.setText("50");
        }
        else  if(iii==2)
        {
            CartItem.setText("2");
            It2.setText("AALU PRATHA");//if (i1.equals(""))
            R2.setText("50");
        }
        else  if(iii==3)
        {
            CartItem.setText("3");
            It3.setText("AALU PRATHA");//if (i1.equals(""))
            R3.setText("50");
        }
        else  if(iii==4)
        {
            CartItem.setText("4");
            It4.setText("AALU PRATHA");//if (i1.equals(""))
            R4.setText("50");
        }
        else  if(iii==5)
        {
            CartItem.setText("5");
            R5.setText("50");
            It5.setText("AALU PRATHA");//if (i1.equals(""))
        }
        else
        {
            Max.setText("*Sorry You cannot add more than 5 Items");
        }
    }//GEN-LAST:event_jLabel278MouseClicked

    private void jLabel279MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel279MouseClicked
        //@LAKSHAY(RA1711003030064)
        Max.setText("");
        iii=iii+1;
        if(iii==1)
        {
            CartItem.setText("1");
            It1.setText("BUTTER NAN");//if (i1.equals(""))
            R1.setText("30");
        }
        else  if(iii==2)
        {
            CartItem.setText("2");
            It2.setText("BUTTER NAN");//if (i1.equals(""))
            R2.setText("30");
        }
        else  if(iii==3)
        {
            CartItem.setText("3");
            It3.setText("BUTTER NAN");//if (i1.equals(""))
            R3.setText("30");
        }
        else  if(iii==4)
        {
            CartItem.setText("4");
            It4.setText("BUTTER NAN");//if (i1.equals(""))
            R4.setText("30");
        }
        else  if(iii==5)
        {
            CartItem.setText("5");
            R5.setText("30");
            It5.setText("BUTTER NAN");//if (i1.equals(""))
        }
        else
        {
            Max.setText("*Sorry You cannot add more than 5 Items");
        }
    }//GEN-LAST:event_jLabel279MouseClicked

    private void jLabel280MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel280MouseClicked
        //@LAKSHAY(RA1711003030064)
        Max.setText("");
        iii=iii+1;
        if(iii==1)
        {
            CartItem.setText("1");
            It1.setText("CHHOLE BHATURE");//if (i1.equals(""))
            R1.setText("40");
        }
        else  if(iii==2)
        {
            CartItem.setText("2");
            It2.setText("CHHOLE BHATURE");//if (i1.equals(""))
            R2.setText("40");
        }
        else  if(iii==3)
        {
            CartItem.setText("3");
            It3.setText("CHHOLE BHATURE");//if (i1.equals(""))
            R3.setText("40");
        }
        else  if(iii==4)
        {
            CartItem.setText("4");
            It4.setText("CHHOLE BHATURE");//if (i1.equals(""))
            R4.setText("40");
        }
        else  if(iii==5)
        {
            CartItem.setText("5");
            R5.setText("40");
            It5.setText("CHHOLE BHATURE");//if (i1.equals(""))
        }
        else
        {
            Max.setText("*Sorry You cannot add more than 5 Items");
        }
    }//GEN-LAST:event_jLabel280MouseClicked

    private void jLabel281MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel281MouseClicked
        //@LAKSHAY(RA1711003030064)
        Max.setText("");
        iii=iii+1;
        if(iii==1)
        {
            CartItem.setText("1");
            It1.setText("CHILLI POTATO");//if (i1.equals(""))
            R1.setText("70");
        }
        else  if(iii==2)
        {
            CartItem.setText("2");
            It2.setText("CHILLI POTATO");//if (i1.equals(""))
            R2.setText("70");
        }
        else  if(iii==3)
        {
            CartItem.setText("3");
            It3.setText("CHILLI POTATO");//if (i1.equals(""))
            R3.setText("70");
        }
        else  if(iii==4)
        {
            CartItem.setText("4");
            It4.setText("CHILLI POTATO");//if (i1.equals(""))
            R4.setText("70");
        }
        else  if(iii==5)
        {
            CartItem.setText("5");
            R5.setText("70");
            It5.setText("CHILLI POTATO");//if (i1.equals(""))
        }
        else
        {
            Max.setText("*Sorry You cannot add more than 5 Items");
        }
    }//GEN-LAST:event_jLabel281MouseClicked

    private void jLabel282MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel282MouseClicked
        //@LAKSHAY(RA1711003030064)
        Max.setText("");
        iii=iii+1;
        if(iii==1)
        {
            CartItem.setText("1");
            It1.setText("PALAK PANEER");//if (i1.equals(""))
            R1.setText("100");
        }
        else  if(iii==2)
        {
            CartItem.setText("2");
            It2.setText("PALAK PANEER");//if (i1.equals(""))
            R2.setText("100");
        }
        else  if(iii==3)
        {
            CartItem.setText("3");
            It3.setText("PALAK PANEER");//if (i1.equals(""))
            R3.setText("100");
        }
        else  if(iii==4)
        {
            CartItem.setText("4");
            It4.setText("PALAK PANEER");//if (i1.equals(""))
            R4.setText("100");
        }
        else  if(iii==5)
        {
            CartItem.setText("5");
            R5.setText("100");
            It5.setText("PALAK PANEER");//if (i1.equals(""))
        }
        else
        {
            Max.setText("*Sorry You cannot add more than 5 Items");
        }
    }//GEN-LAST:event_jLabel282MouseClicked

    private void jLabel283MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel283MouseClicked
        //@LAKSHAY(RA1711003030064)
        Max.setText("");
        iii=iii+1;
        if(iii==1)
        {
            CartItem.setText("1");
            It1.setText("BREAD PIZZA");//if (i1.equals(""))
            R1.setText("30");
        }
        else  if(iii==2)
        {
            CartItem.setText("2");
            It2.setText("BREAD PIZZA");//if (i1.equals(""))
            R2.setText("30");
        }
        else  if(iii==3)
        {
            CartItem.setText("3");
            It3.setText("BREAD PIZZA");//if (i1.equals(""))
            R3.setText("30");
        }
        else  if(iii==4)
        {
            CartItem.setText("4");
            It4.setText("BREAD PIZZA");//if (i1.equals(""))
            R4.setText("30");
        }
        else  if(iii==5)
        {
            CartItem.setText("5");
            R5.setText("30");
            It5.setText("BREAD PIZZA");//if (i1.equals(""))
        }
        else
        {
            Max.setText("*Sorry You cannot add more than 5 Items");
        }
    }//GEN-LAST:event_jLabel283MouseClicked

    private void jLabel284MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel284MouseClicked
        //@LAKSHAY(RA1711003030064)
        Max.setText("");
        iii=iii+1;
        if(iii==1)
        {
            CartItem.setText("1");
            It1.setText("MALAI KOFTA");//if (i1.equals(""))
            R1.setText("80");
        }
        else  if(iii==2)
        {
            CartItem.setText("2");
            It2.setText("MALAI KOFTA");//if (i1.equals(""))
            R2.setText("80");
        }
        else  if(iii==3)
        {
            CartItem.setText("3");
            It3.setText("MALAI KOFTA");//if (i1.equals(""))
            R3.setText("80");
        }
        else  if(iii==4)
        {
            CartItem.setText("4");
            It4.setText("MALAI KOFTA");//if (i1.equals(""))
            R4.setText("80");
        }
        else  if(iii==5)
        {
            CartItem.setText("5");
            R5.setText("80");
            It5.setText("MALAI KOFTA");//if (i1.equals(""))
        }
        else
        {
            Max.setText("*Sorry You cannot add more than 5 Items");
        }

    }//GEN-LAST:event_jLabel284MouseClicked

    private void jLabel287MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel287MouseClicked
        //@LAKSHAY(RA1711003030064)

        if(iii==1)
        {
            a=Integer.valueOf(R1.getText());
            b=0;
            c=0;
            d=0;
            e=0;
        }
        else if(iii==2)
        {
            a=Integer.valueOf(R1.getText());

            b=Integer.valueOf(R2.getText());
            c=0;d=0;e=0;
        }

        else if(iii==3)
        {
            a=Integer.valueOf(R1.getText());

            b=Integer.valueOf(R2.getText());
            c=Integer.valueOf(R3.getText());
            d=0;
            e=0;

        }
        else if(iii==4)
        {
            a=Integer.valueOf(R1.getText());

            b=Integer.valueOf(R2.getText());
            c=Integer.valueOf(R3.getText());
            e=0;
            d=Integer.valueOf(R4.getText());
        }
        //c=Integer.valueOf(R3.getText());
        //d=Integer.valueOf(R4.getText());
        //e=Integer.valueOf(R5.getText());
        else if(iii==5)
        {
            a=Integer.valueOf(R1.getText());

            b=Integer.valueOf(R2.getText());
            c=Integer.valueOf(R3.getText());
            e=Integer.valueOf(R5.getText());
            d=Integer.valueOf(R4.getText());

        }
        int f=a+b+c+d+e;
        if(f>=100)
        {
            CheckOut.setText("PROCEED TO CHECKOUT");
        }
        if(f<100)
        {
            Max.setText("Order value must be above 100");
        }
        else
        {
            String s=Integer.toString(f);
            GrandTotal.setText("GRAND TOTAL");
            Totalrs.setText(s);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel287MouseClicked

    private void CheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckOutActionPerformed
        Payment h=new Payment();
        h.setVisible(true);
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_CheckOutActionPerformed
static int iii=0;
int a,b,c,d,e;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Up14.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Up14.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Up14.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Up14.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Up14().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cart;
    private javax.swing.JLabel CartItem;
    private javax.swing.JButton CheckOut;
    private javax.swing.JLabel GrandTotal;
    private javax.swing.JLabel It1;
    private javax.swing.JLabel It2;
    private javax.swing.JLabel It3;
    private javax.swing.JLabel It4;
    private javax.swing.JLabel It5;
    private javax.swing.JLabel Max;
    private javax.swing.JLabel Max9;
    private javax.swing.JLabel R1;
    private javax.swing.JLabel R2;
    private javax.swing.JLabel R3;
    private javax.swing.JLabel R4;
    private javax.swing.JLabel R5;
    private javax.swing.JLabel Totalrs;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel263;
    private javax.swing.JLabel jLabel264;
    private javax.swing.JLabel jLabel265;
    private javax.swing.JLabel jLabel266;
    private javax.swing.JLabel jLabel267;
    private javax.swing.JLabel jLabel268;
    private javax.swing.JLabel jLabel269;
    private javax.swing.JLabel jLabel270;
    private javax.swing.JLabel jLabel271;
    private javax.swing.JLabel jLabel272;
    private javax.swing.JLabel jLabel273;
    private javax.swing.JLabel jLabel274;
    private javax.swing.JLabel jLabel275;
    private javax.swing.JLabel jLabel276;
    private javax.swing.JLabel jLabel277;
    private javax.swing.JLabel jLabel278;
    private javax.swing.JLabel jLabel279;
    private javax.swing.JLabel jLabel280;
    private javax.swing.JLabel jLabel281;
    private javax.swing.JLabel jLabel282;
    private javax.swing.JLabel jLabel283;
    private javax.swing.JLabel jLabel284;
    private javax.swing.JLabel jLabel285;
    private javax.swing.JLabel jLabel286;
    private javax.swing.JLabel jLabel287;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    // End of variables declaration//GEN-END:variables
}
